#!/usr/bin/env zsh
make_prereqs() {
    # Make "make" figure out what files it's interested in.
    echo "Makefile"
    find $MAKEWATCH
    make -dnr $* | tr ' ' '\n' | \
        grep ".*'.$" | grep -o '\w.*\b'
}

prereq_files() {
    # prerequisites mentioned in a Makefile
    # that are extant files
    echo ' '
    for f in `make_prereqs $* | sort -u`; do
        [ -e $f ] && echo -n "$f ";
    done
    echo
}

clean_and_commit() {
    make clean
    chmod +x ./.watcher_env
    source ./.watcher_env
    read commit_msg
    if [[ -z "$commit_msg" ]]
    then
        git commit -S -am "auto commit $COMMIT"
        git push -u origin main
    fi
    COMMIT=$((COMMIT+1))
    echo "export COMMIT=$COMMIT" > ./.watcher_env
    exit 0
}

make $*
trap clean_and_commit SIGINT SIGTERM
inotifywait -e close_write -e move --quiet $(prereq_files $*)
sleep 1
exec $0