#!/usr/bin/env zsh
make_prereqs() {
    # Make "make" figure out what files it's interested in.
    echo "Makefile"
    find $MAKEWATCH
    make -dnr $* | tr ' ' '\n' | \
        grep ".*'.$" | grep -o '\w.*\b'
}

prereq_files() {
    # prerequisites mentioned in a Makefile
    # that are extant files
    echo ' '
    for f in `make_prereqs $* | sort -u`; do
        [ -e $f ] && echo -n "$f ";
    done
    echo
}

clean_and_commit() {
    make clean
    git commit -S -am "auto commit"
    git push -u origin main
}

make $*
trap clean_and_commit SIGINT SIGTERM
inotifywait -e close_write -e move --quiet $(prereq_files $*)
sleep 1
exec $0